// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Player_f14974ba2498d4ab0b5812581fe716bdIndex = 0;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Player_f14974ba2498d4ab0b5812581fe716bd", 0 },

		};
	}
}
